spring.application.name=cloud-stream
server.port=8083
spring.cloud.function.definition=textConsumer;textProducer
spring.cloud.stream.bindings.textConsumer-in-0.destination=text-topic
spring.cloud.stream.bindings.textConsumer-in-0.group=text-group
spring.cloud.stream.bindings.textProducer-out-0.destination=text-topic
spring.cloud.stream.kafka.binder.brokers=localhost:9092
