spring:
  application:
  name: project-cake
  server.port: 8081

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: cake
    password: cake123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
